// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    String number = args[0];
		int n = Integer.valueOf(number);
		
		int count_less = 0;
		int count_more = 0;

		for (int i = 0; i<n; i++) {
		    double rand = Math.random();
		    if (rand > 0.5){
				count_more += 1;
			}
		    else{
				count_less += 1;
			}	
		}
		double total = n;

		double ratio_less = count_less / total;

		double ratio_more = count_more / total;
		double avg = 0.0;
		if (ratio_less < ratio_more) {
		    avg = (ratio_less / ratio_more);
		}
		else{
			avg = (ratio_more / ratio_less);
		}

		System.out.println("> 0.5:" + " " + count_more+ " times");
		System.out.println("< 0.5:" + " " + count_less + " times");
		System.out.println("Ratio:" + " " + avg);
		    
	}
}
